import turtle
screen=turtle.Screen()
screen.setup(600,600)
screen.bgcolor("blue")
board=turtle.Turtle()
board.forward(100)
board.left(90)
board.forward(50)
board.left(90)
board.forward(100)
board.left(90)
board.forward(50)
turtle.done()
